trigger:
- poc

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:

- stage: Build
  displayName: Build, Scan, Push Image

  jobs:
  - job: Build
    displayName: Build, Scan, Push Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: CmdLine@2
      displayName: 'Show ACR Registry'
      inputs:
        script: 'echo "ACR Registry: $(ACR_REGISTRY)"'
  
    - task: Docker@2
      displayName: Build Image
      inputs:
        command: build
        repository: $(ACR_REGISTRY)/poc-demo
        tags: $(Build.BuildId)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)'
    - task: CmdLine@2
      displayName: Pull Aqua Scanner Image
      inputs: 
        script: |-
          docker image ls 
          docker login registry.aquasec.com -u $(AQUA_USER) -p $(AQUA_PASSWORD)
          docker pull registry.aquasec.com/scanner:2022.4
    - task: aquasecScanner@4
      displayName: Aqua Image Scanner
      inputs:
        image: $(ACR_REGISTRY)/poc-demo:$(Build.BuildId)
        register: false
        hideBase: false
        showNegligible: false
        scanner: 'registry.aquasec.com/scanner:2022.4'
        connection: 'pos-devops'
        runOptions: ' -e BUILD_JOB_NAME=$(Build.Repository.Name)'

    - task: CmdLine@2
      displayName: Push Image to ACR
      inputs: 
        script: |-
          docker login -u systexacr -p $(ACR_PASSWORD) systexacr.azurecr.io
          docker push $(ACR_REGISTRY)/poc-demo:$(Build.BuildId)